### ISSUE TITLE
Fail to call gf_scc

### ISSUE THREAD

**Issue by harryprince** [kevinykuo/sparklygraphs#7]
I have tried call gf_scc use sparklygraphs api, however, I failed.
```
graph_tbl %>% 
    head(100) %>% 
    gf_scc(10)
```

it tells me 

```
Error: java.lang.Exception: No matched method found for class org.graphframes.lib.StronglyConnectedComponents.maxIter
```
In that, I turn to try call the api from origin scala version:

```
   graph_tbl %>% 
         head(100) %>% 
        spark_graphframe() %>% 
       invoke("stronglyConnectedComponents") %>% 
      invoke("getClass") %>%
      invoke("getMethods")
```

console record is below:

```
[[1]]
<jobj[380]>
  java.lang.reflect.Method
  public org.graphframes.lib.StronglyConnectedComponents org.graphframes.lib.StronglyConnectedComponents.maxIter(int)
```
it print the maxIter is a method of SCC class, however I still fail to call the api in the original way, I am using scala 1.1 and spark 2.2.1

**Comment by kevinykuo** [comment]
For now, could you try passing an integer explicitly for `max_iter`? E.g.
```
graph_tbl %>% 
    head(100) %>% 
    gf_scc(10L)
```

I'll be working on sparklygraphs (hopefully) soon and will make sure this gets addressed.

**Comment by harryprince** [comment]
it will failed like this:

```
Error: java.lang.IllegalArgumentException: invalid method stronglyConnectedComponents for object 176
```

**Comment by kevinykuo** [comment]
Oh sorry, if `graph_tbl` is an edges table you'll need to get a `GraphFrame` first by calling `gf_graphframe()`. If it's a `GraphFrame` you wouldn't want to call `head()` on it, since sparklygraphs doesn't provide a `head()` method so it'd return a list. If `graph_tbl` is indeed a data frame, try
```
graph_tbl %>% 
    head(100) %>% 
    gf_graphframe(edges = .) %>%
    gf_scc(10L)
```

Let me know if this works. If not I'll need a sample of your data to investigate further.

**Comment by harryprince** [comment]
I will try it again.

I am using `tidygraph` too, which is a local version. I am happy to see if `sparklygraphs` can integrate with `tidygraph` just like sparklyr and dplyr. Maybe tidygraph is the most consistent api and user friendly that I have met.
